version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://user:password@db:5432/homekey
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homekey
    volumes:
      - db_data:/var/lib/postgresql/data
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
  db_data: